_target_: src.trm.TRM
backbone: mlp
d_hidden: 512
n_heads: 8
n_layers: 2
n_puzzle_embedding_tokens: 16
deep_supervision_steps: 16
deep_supervision_exploration_prob: 0.1
n_reasoning_steps: 3
n_latent_steps: 6
seq_loss_weight: 1.0
q_halt_loss_weight: 0.5
dropout: 0.0